apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  labels:
    app: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
