apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 977
      containers:
        - name: searxng
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SEARXNG_BASE_URL
              value: "https://{{ .Values.service.host }}/"
            - name: SEARXNG_PORT
              value: "8080"
          volumeMounts:
            - name: searxng-settings
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
            - name: searxng-limiter
              mountPath: /etc/searxng/limiter.toml
              subPath: limiter.toml
            - name: searxng-cache
              mountPath: /var/cache/searxng
      volumes:
        - name: searxng-settings
          secret:
            secretName: searxng-settings
        - name: searxng-limiter
          configMap:
            name: searxng-limiter
        - name: searxng-cache
          persistentVolumeClaim:
            claimName: searxng-cache

