apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-settings
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-settings
    creationPolicy: Owner
  data:
    - secretKey: settings.yml
      remoteRef:
        key: {{ .Release.Name }}/settings
        property: yaml

