apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-postgres
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Release.Name }}/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-oidc
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: client-id
      remoteRef:
        key: {{ .Release.Name }}/oidc
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: {{ .Release.Name }}/oidc
        property: client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-admin
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: email
      remoteRef:
        key: {{ .Release.Name }}/admin
        property: email
    - secretKey: password
      remoteRef:
        key: {{ .Release.Name }}/admin
        property: password
    - secretKey: api-password
      remoteRef:
        key: {{ .Release.Name }}/admin
        property: api-password

