image:
  repository: nousresearch/hermes-agent
  tag: sha-825bd50e6be1bfbde38d8337c599952da32b9a92

service:
  host: hermes.cluster.asaio
  port: 80
  targetPort: 8080

dashboard:
  enabled: true
  host: hermes-dashboard.cluster.asaio
  port: 9119
  targetPort: 9119
  bindHost: 0.0.0.0

persistence:
  size: 2Gi
  storageClassName: nfs-subdir
  accessModes:
    - ReadWriteOnce
  annotations:
    k8s-sigs.io/nfs-directory-mode: "0770"
    k8s-sigs.io/nfs-directory-uid: "10000"
    k8s-sigs.io/nfs-directory-gid: "10000"

podSecurityContext:
  fsGroup: 10000
  fsGroupChangePolicy: OnRootMismatch

resources: {}

extraEnv: []
extraArgs: []

externalSecrets:
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  forgejoToken:
    key: hermes/forgejo
    property: token

httproute:
  enabled: true
  gatewayName: traefik-gateway
  gatewayNamespace: traefik
  sectionName: web
