image:
  repository: nousresearch/hermes-agent
  tag: dafe443beba74384871e2c79d5b17db8bc51880e

service:
  host: hermes.asaio
  port: 80
  targetPort: 8080

persistence:
  size: 2Gi
  storageClassName: nfs-subdir
  accessModes:
    - ReadWriteOnce

resources: {}

extraEnv: []
extraArgs: []

externalSecrets:
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  forgejoToken:
    key: hermes/forgejo
    property: token

httproute:
  enabled: true
  gatewayName: traefik-gateway
  gatewayNamespace: traefik
  sectionName: web
