apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: example-sync
  data:
  - secretKey: postgres-password
    remoteRef:
      key: tandoor/postgres
      property: password

  # metadataPolicy to fetch all the labels in JSON format
  - secretKey: tags
    remoteRef:
      metadataPolicy: Fetch
      key: tandoor/postgres

  # metadataPolicy to fetch a specific label (dev) from the source secret
  - secretKey: developer
    remoteRef:
      metadataPolicy: Fetch
      key: tandoor/postgres
      property: dev
