image:
  repository: vabene1111/recipes
  tag: 2.6.1

tandoor:
  host: tandoor.asaio.net

externalSecrets:
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore

persistence:
  staticfiles:
    size: 5Gi
  mediafiles:
    size: 10Gi

